### ISSUE TITLE
Logging Update

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/asn1_codec#21]
The asn1_codec module currently uses a combination of logging, having separate files for error and info level logging as well as still logging manually to the std::cerr and std::cout. This should be consolidated to a single stream of logging, sending data to the standard console outputs for ease of consumption by Docker/K8s. Additionally, the module should allow for overriding the logging level (configuration file setting) to prevent logging size issues down the road.

**Comment by dmccoystephenson** [comment]
The problem has been solved with the following improvements:

- Log statements now go to a single file when file logging is enabled.
- We have stopped using standard output (wherever possible) in #28.
- The logging level of the ACM can now be overridden.

**Comment by TonyEnglish** [comment]
Thank you for addressing!
